
/* - Pedro Luis - 30/10/2023

CREATE DATABASE BDJOGO_ATIVIDADEFINAL;
use BDJOGO_ATIVIDADEFINAL;

CREATE TABLE CLASSE(
ID_CLASSE INT PRIMARY KEY auto_increment,
DESCRICAO_CLASSE VARCHAR(50));

CREATE TABLE PERSONAGEM(
ID_PERSONAGEM INT PRIMARY KEY AUTO_INCREMENT,
NOME_PERSONAGEM VARCHAR (80) NOT NULL,
NIVEL_PERSONAGEM INT, 
MANA_PERSONAGEM INT,
ATAQUE_PERSONAGEM INT,
AGILIDADE_PERSONAGEM INT, 
VITALIDADE_PERSONAGEM INT, 
ID_CLASSE INT, 
CONSTRAINT FK_PERSONAGEM_CLASSE FOREIGN KEY (ID_CLASSE)
REFERENCES CLASSE (ID_CLASSE));