/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ifpr
 */
public class atv3AlunoMedia extends javax.swing.JFrame {

    /**
     * Creates new form atv3AlunoMedia
     */
    public atv3AlunoMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfBioPB = new javax.swing.JTextField();
        tfBioSB = new javax.swing.JTextField();
        tfBioTB = new javax.swing.JTextField();
        tfBioMedia = new javax.swing.JTextField();
        tfBioResultado = new javax.swing.JTextField();
        tfMatPB = new javax.swing.JTextField();
        tfMatSB = new javax.swing.JTextField();
        tfMatTB = new javax.swing.JTextField();
        tfMatMedia = new javax.swing.JTextField();
        tfMatResultado = new javax.swing.JTextField();
        tfPortPB = new javax.swing.JTextField();
        tfPortSB = new javax.swing.JTextField();
        tfPortTB = new javax.swing.JTextField();
        tfPortMedia = new javax.swing.JTextField();
        tfPortResultado = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Medias de notas do aluno");

        jLabel2.setText("1 Bimestre");

        jLabel3.setText("2 Bimestre");

        jLabel4.setText("3 Bimestre");

        jLabel5.setText("Media");

        jLabel6.setText("Resultado");

        jLabel7.setText("Biologia");

        jLabel8.setText("Português");

        jLabel9.setText("Matemática");

        jButton1.setText("Ver resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfBioPB.setText("*");

        tfBioSB.setText("*");

        tfBioTB.setText("*");
        tfBioTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBioTBActionPerformed(evt);
            }
        });

        tfBioMedia.setText("*");
        tfBioMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBioMediaActionPerformed(evt);
            }
        });

        tfBioResultado.setText("*");
        tfBioResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBioResultadoActionPerformed(evt);
            }
        });

        tfMatPB.setText("*");

        tfMatSB.setText("*");
        tfMatSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatSBActionPerformed(evt);
            }
        });

        tfMatTB.setText("*");
        tfMatTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatTBActionPerformed(evt);
            }
        });

        tfMatMedia.setText("*");
        tfMatMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatMediaActionPerformed(evt);
            }
        });

        tfMatResultado.setText("*");
        tfMatResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatResultadoActionPerformed(evt);
            }
        });

        tfPortPB.setText("*");
        tfPortPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortPBActionPerformed(evt);
            }
        });

        tfPortSB.setText("*");
        tfPortSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortSBActionPerformed(evt);
            }
        });

        tfPortTB.setText("*");
        tfPortTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortTBActionPerformed(evt);
            }
        });

        tfPortMedia.setText("*");
        tfPortMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortMediaActionPerformed(evt);
            }
        });

        tfPortResultado.setText("*");
        tfPortResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton2)
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfBioPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfMatPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPortPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfBioSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPortSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfBioTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPortTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfBioMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPortMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPortResultado)
                            .addComponent(tfMatResultado)
                            .addComponent(jLabel6)
                            .addComponent(tfBioResultado))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfBioPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBioSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBioTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBioMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBioResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfMatPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMatSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMatTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMatMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMatResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfPortPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPortSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPortTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPortMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPortResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atv3Aluno a = new atv3Aluno();     
        
        a.bNota1 = Double.parseDouble(tfBioPB.getText());
        a.bNota2 = Double.parseDouble(tfBioSB.getText());
        a.bNota3 = Double.parseDouble(tfBioTB.getText());      
        
        a.bMedia = (a.bNota1+a.bNota2+a.bNota3)/3;
        
        tfBioMedia.setText(a.bMedia.toString());
        tfBioResultado.setText(a.ExibirMediaB());
        
        
        a.mNota1 = Double.parseDouble(tfMatPB.getText());
        a.mNota2 = Double.parseDouble(tfMatSB.getText());
        a.mNota3 = Double.parseDouble(tfMatTB.getText());      
        
        a.mMedia = (a.mNota1+a.mNota2+a.mNota3)/3;
        
        tfMatMedia.setText(a.mMedia.toString());
        tfMatResultado.setText(a.ExibirMediaM());
        
        a.pNota1 = Double.parseDouble(tfPortPB.getText());
        a.pNota2 = Double.parseDouble(tfPortSB.getText());
        a.pNota3 = Double.parseDouble(tfPortTB.getText());      
        
        tfPortMedia.setText(a.pMedia.toString());
        a.pMedia = (a.pNota1+a.pNota2+a.pNota3)/3;
        
        tfPortResultado.setText(a.ExibirMediaP());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfBioTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBioTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBioTBActionPerformed

    private void tfBioMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBioMediaActionPerformed
        tfBioMedia.setEnabled(false);
    }//GEN-LAST:event_tfBioMediaActionPerformed

    private void tfBioResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBioResultadoActionPerformed
        tfBioResultado.setEnabled(false);
    }//GEN-LAST:event_tfBioResultadoActionPerformed

    private void tfMatSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatSBActionPerformed

    private void tfMatTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatTBActionPerformed

    private void tfMatMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatMediaActionPerformed
        tfMatMedia.setEnabled(false);
    }//GEN-LAST:event_tfMatMediaActionPerformed

    private void tfMatResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatResultadoActionPerformed
        tfMatResultado.setEnabled(false);
    }//GEN-LAST:event_tfMatResultadoActionPerformed

    private void tfPortPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPortPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPortPBActionPerformed

    private void tfPortSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPortSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPortSBActionPerformed

    private void tfPortTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPortTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPortTBActionPerformed

    private void tfPortMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPortMediaActionPerformed
        tfPortMedia.setEnabled(false);
    }//GEN-LAST:event_tfPortMediaActionPerformed

    private void tfPortResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPortResultadoActionPerformed
        tfPortResultado.setEnabled(false);
    }//GEN-LAST:event_tfPortResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atv3AlunoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atv3AlunoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atv3AlunoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atv3AlunoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atv3AlunoMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfBioMedia;
    private javax.swing.JTextField tfBioPB;
    private javax.swing.JTextField tfBioResultado;
    private javax.swing.JTextField tfBioSB;
    private javax.swing.JTextField tfBioTB;
    private javax.swing.JTextField tfMatMedia;
    private javax.swing.JTextField tfMatPB;
    private javax.swing.JTextField tfMatResultado;
    private javax.swing.JTextField tfMatSB;
    private javax.swing.JTextField tfMatTB;
    private javax.swing.JTextField tfPortMedia;
    private javax.swing.JTextField tfPortPB;
    private javax.swing.JTextField tfPortResultado;
    private javax.swing.JTextField tfPortSB;
    private javax.swing.JTextField tfPortTB;
    // End of variables declaration//GEN-END:variables
}
